### ISSUE TITLE
App doesn't let you login in landscape orientation on Nexus 5

### ISSUE THREAD

**Issue by mattl** [creativecommons/list#105]
Maybe other phones too.

@billymeinke -- how does it look on your Note in landscape mode?

**Comment by billymeinke** [comment]
Same issue on the Note.

The "I already have an account" text disappears in landscape.

**Comment by perpetuatingcuriosity** [comment]
Keeping the design fixed to portrait for now (except photo taking, of course).

**Comment by perpetuatingcuriosity** [comment]
#326 will cover this issue.
