### ISSUE TITLE
Google Analytics tracking Activity usage

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#108]

**Comment by mattl** [comment]
Pushing this way out for now, so I can loop @sarahpearson in. We need to think about the privacy implications of this.

I'd like to make it opt-in, if possible. Also, easy to completely turn off in an apk build, so we can produce a Google Analytics-less version of the app.

**Comment by perpetuatingcuriosity** [comment]
@sarahpearson I have the code to implement this when the terms are ready.

**Comment by sarahpearson** [comment]
@perpetuatingcuriosity can you explain more about what this would be used for? CC's privacy policy (http://creativecommons.org/privacy) has certain principles we have committed to as an org, and one of those is not collecting and retaining more personal information than is necessary to perform the services we are providing for them. I'm concerned this might violate that principle, but I would need to know more.

**Comment by perpetuatingcuriosity** [comment]
@sarahpearson The main reason to use Google Analytics would be to keep track of how the app is running, how it’s being used, and how frequently. We can collect data on which screens of the app are being used, how often, and for how long. We can also see how many users we have (new users or returning users), and log when the app crashes to help quickly identify problems.

This could help out with:
- deciding which problems to tackle first
- deciding what features to add first
(What are people using the most/least? And why?)

With the default settings, you also receive data on: 
- How many users we have: new users vs. returning users
- What model of device is running is the app
- What version of Android a device is being used
- What network operators the device is using
- What screen resolutions do the devices have (which is can also be really handy when deciding what layout problems to tackle first)

There’s also a real-time viewing of the app being used.

This is pretty much just the basic implementation of Google Analytics in the app, but as far as I can tell there isn’t any further collection of data unless you add it yourself.

**Comment by perpetuatingcuriosity** [comment]
There’s more info at: http://www.google.ca/analytics/mobile/

I’ve been testing it though and the above data (minus crash data) is what I’ve been receiving in tests.

**Comment by sarahpearson** [comment]
Thanks for the info! Is the data you are seeing connected to individual CCIDs? If it does not identify what user is doing what, then I think it would be consistent with our policies.

**Comment by perpetuatingcuriosity** [comment]
There won’t be any data connected to CCIDs. The data is the same whether or not a user is logged in to the app or not. The only identifiers as to who the user is might be: phone model, country where the phone is being used, the network the phone is being used on.

**Comment by mattl** [comment]
This would tie the app to Google Play Services, which we're avoiding. I'll move to the the laterbase for now, so we can consider it later. We get some of this info in the web server logs.

**Comment by peterspdx** [comment]
We thought about google analytics back when we first established privacy principles with the major overhaul of privacy years ago (recently tweaked to reference CCID).  We called out that we'd use third party analytic providers, as you all know:  CC may use a third
party analytics provider to help us collect and analyze non personal
browsing information through operation of our Services for those same
purposes.  

So long as what's gathered is consistent with that, and there's no linking to the individual CCID or OpenID as stated in our policy, this seems fine.

**Comment by perpetuatingcuriosity** [comment]
The privacy section of the Google Analytics policy seems to already cover this (http://www.google.com/analytics/terms/us.html): 

“You will not (and will not allow any third party to) use the Service to track, collect or upload any data that personally identifies an individual (such as a name, email address or billing information), or other data which can be reasonably linked to such information by Google. You will have and abide by an appropriate Privacy Policy and will comply with all applicable laws, policies, and regulations relating to the collection of information from Visitors. You must post a Privacy Policy and that Privacy Policy must provide notice of Your use of cookies that are used to collect data. You must disclose the use of Google Analytics, and how it collects and processes data. This can be done by displaying a prominent link to the site “How Google uses data when you use our partners' sites or apps”, (located at www.google.com/policies/privacy/partners/, or any other URL Google may provide from time to time). You must not circumvent any privacy features (e.g., an opt-out) that are part of the Service.”

**Comment by mattl** [comment]
This is in.
