### ISSUE TITLE
Support HTTP error code responses for all API requests

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#109]

**Comment by perpetuatingcuriosity** [comment]
@mattl Would it possible to get just the responses working for POST photos before the end of the week?

**Comment by mattl** [comment]
Yep. I'll try and get that in today.

**Comment by mattl** [comment]
Have it in there, but it's not working correctly... I'll see if I can fix it up.

**Comment by mattl** [comment]
Okay, it actually turns out it does work I just didn't pull the files to the server. Sigh.

**Comment by mattl** [comment]
curl --data-urlencode "filedata=`base64 -w0 cat.jpg`" -X POST https://thelist.creativecommons.org/api/photos/1/42

This is working for me, and after a minute or so when the image is processed, completed = 1 and it disappears from my list.

**Comment by mattl** [comment]
Moving this to the next release. For now we have it where we need it.

**Comment by mattl** [comment]
Can you look over the existing API tickets, and let me know what you're expecting when things fail?
