### ISSUE TITLE
iPad

### ISSUE THREAD

**Issue by pgstacey** [creativecommons/list#117]
Tried using the web version of The List with my iPad. Everything works great except, if I choose to take a photo, and then click on the Upload button it appears to upload but at the end of the upload process does not return me to The List it simply goes to a blank white screen.

Paul

**Comment by mattl** [comment]
Hey Paul -- can you try again? The white screen bug is something which seems to plague everyone, not just iPad users...

**Comment by pgstacey** [comment]
Tried it just now.
No change still white screen - like winter in Canada, or, today at least,
fog in Vancouver.

Paul

On Thu, Jan 8, 2015 at 11:59 AM, Matt Lee <notifications@github.com> wrote:

> Hey Paul -- can you try again? The white screen bug is something which
> seems to plague everyone, not just iPad users...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/list/issues/117#issuecomment-69239266>
> .
>



-- 
Paul Stacey
Associate Director of Global Learning
Creative Commons
pstacey@creativecommons.org

State of the Commons Report https://stateof.creativecommons.org/report/
Get Creative Commons Updates http://bit.ly/commonsnews
