### ISSUE TITLE
Need complete flag as soon as an image is uploaded and error flag if processing fails

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#121]
When an image is uploaded:
complete = 1

(Should have a value of 1 immediately so if the user list in the app needs to be updated while processing is still happening, the list will appear accurate.)

If processing fails:
complete = null (again)
+
error = 1

**Comment by mattl** [comment]
Slight tweak on this. When you upload an image, it immediately goes to complete = 1. If it fails, complete = 2.

**Comment by perpetuatingcuriosity** [comment]
Maybe we can change “complete” to “status” so it’s a bit more clear?

**Comment by perpetuatingcuriosity** [comment]
Seems to be working. @mattl Maybe we can test an error later though?

**Comment by mattl** [comment]
try uploading a PNG, that should do it.

**Comment by perpetuatingcuriosity** [comment]
@mattl Doesn’t seem like items aren’t being marked at complete (“2”) right away. 

Sometimes I can upload 2 photos one after the other to the same item before it disappears from the list.

**Comment by mattl** [comment]
They should be marked as 0 right away, and then 2 if they are good to go,
and then 1 if there's an error.

---
Matt Lee
Creative Commons
Boston, MA, USA

**Comment by perpetuatingcuriosity** [comment]
They should be marked at 0 by default and 2 as soon as a photo is uploaded.

I’m saying it doesn’t change to 2 so when I request the user’s list after a photo upload, the item is still there. And the complete value is 0 even though it should be 2.
