### ISSUE TITLE
Check for file types other than jpg

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#124]
Prevent users from entering the upload process needlessly. Probably just a dialog

**Comment by perpetuatingcuriosity** [comment]
If we won’t be supporting other file types #154, I’ll like to add a check before sending a POST photo request

**Comment by mattl** [comment]
okay :) curious how you'll do this.

**Comment by perpetuatingcuriosity** [comment]
Just checking the file type. Later on, maybe the api can send a detailed error response.
