### ISSUE TITLE
Deleting items quickly messes with the view

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#129]

**Comment by perpetuatingcuriosity** [comment]
Fixed: no items left behind. Still need to work on item dividers messing with the view.

**Comment by mattl** [comment]
Dividers aren't super important.

**Comment by perpetuatingcuriosity** [comment]
I think this one has been good for a while, reopen if you’re having an issue. 

I re-added dividers, and they seem to be displaying without issues :)
