### ISSUE TITLE
Evaluate ACRA for 0.3 release

### ISSUE THREAD

**Issue by mattl** [creativecommons/list#130]
http://www.acra.ch/

**Comment by perpetuatingcuriosity** [comment]
So far ACRA seems to be just for crash reporting. Seems simple enough to set up within the app, but to view results it requires you to host a server to running their webapp. 

Seeing as Google Analytics has built-in reporting for exceptions and is able to track general app usage (not just crash data), I think it would be worth it to try that first. (See recent post in #108: shouldn’t be problem policy-wise)

**Comment by perpetuatingcuriosity** [comment]
@mattl There was a concern about using Google Analytics w/ non-Play services devices.

Their documentation says it should be fine: https://developers.google.com/analytics/devguides/collection/android/v4/

![screen shot 2015-02-02 at 2 50 50 pm](https://cloud.githubusercontent.com/assets/6563209/6007832/248c9cc2-aaeb-11e4-9e4a-e27c3686de0a.png)

If we need better bug reporting we can reconsider acra, but going to close this for now.

**Comment by mattl** [comment]
What's local dispatching? Does that mean we have to do something to get
those results?
