### ISSUE TITLE
List hangs while uploading image (v. 0.1)

### ISSUE THREAD

**Issue by ryanmerkley** [creativecommons/list#131]
After taking a photo, and selecting upload, the list hangs and crashes.

**Comment by perpetuatingcuriosity** [comment]
@ryanmerkley Just tested this while logging in, and after logging in without problems. What phone and OS are you using?

**Comment by ryanmerkley** [comment]
Android Nexus 5, v 5.0.1

To be specific, on upload the spinning circle goes for a very (very) long
time, the screen darkens, and when I wake the phone the app crashes.

**Comment by perpetuatingcuriosity** [comment]
Think this has been resolved. Tested on 2 devices here as well. Reopen if I’m wrong!
