### ISSUE TITLE
Add an “about the app” item to settings menu

### ISSUE THREAD

**Issue by ryanmerkley** [creativecommons/list#132]
Please create an "About the app" item that users can access from the settings menu. It would contain, at a minimum:

- Author information: "This app is developed by Creative Commons ..."
- Link to the licensing/attribution info: "All images created and uploaded using the List can be used and re-used by anyone, so long as they attribute the work of the author. You set your attribution information here. The List uses Creative Commons' CC BY "for attribution" license."
- Link to ToS
- How to help and file a bug: "The List is an free software project of Creative Commons. Contributions are welcome, from writing code, to filing bugs. Our GitHub repo is here."
- Note about partners (Knight, IA): "The app is created with the generous support of the Knight Foundation, and partners like the Internet Archive.
- Donation link: "Creative Commons is a global non-profit, supported by generous donations from people just like you who believe in shared content. Please consider making a donation today."

**Comment by mattl** [comment]
#139

**Comment by mattl** [comment]
I'll do this for the web app first.

**Comment by mattl** [comment]
We need something like this:

## Download The List 

<p><a
href="https://github.com/creativecommons/list/archive/master.zip"
class="btn btn-success">Download The List source code</a>.</p>

<p>This program is free software: you can redistribute it and/or
modify it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.</p>

<p>This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the <a
href="http://www.gnu.org/licenses/agpl-3.0.html">GNU Affero General
Public License</a> for more details.</p>

**Comment by perpetuatingcuriosity** [comment]
Done.
