### ISSUE TITLE
Retry button if upload fails during upload screen

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#133]
Not the same as #146. This is a retry option if the photo upload fails as the user is trying to upload (rather than failing and then reappearing in a user’s list later on).

**Comment by mattl** [comment]
I'm not clear how this is different from #146

**Comment by perpetuatingcuriosity** [comment]
They may not be different now that we’re changing how we show upload progress. Once I figure this out I’ll close one of these.

**Comment by perpetuatingcuriosity** [comment]
Won’t be a problem with the new progress bar + notifications
