### ISSUE TITLE
Need to communicate/confirm password reset

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#134]
Going to also need to link to this page in the android app.

**Comment by mattl** [comment]
We already have it here: https://login.creativecommons.org/pass.php?worlds-a-dress

You can just send the email address as a POST variable "email" to https://login.creativecommons.org/reset-me.php

**Comment by wchwd** [comment]
It would be great if there were some kind of feedback for users using the "forgot password" feature. Submitting the reset password form sends the user back to the login screen without any indication that anything has happened.

The CCID reset password emails also consistently end up in my spam folder. Google has some suggestions on how to prevent that: https://support.google.com/mail/answer/81126?hl=en#authentication

**Comment by mattl** [comment]
Emails aren't going through the correct mail server yet. Also, the reset
password page looks like crap. We'll get that fixed for milestone 0.3

**Comment by wchwd** [comment]
Great! Thanks.

**Comment by mattl** [comment]
https://github.com/creativecommons/CCID-cas/issues/2
