### ISSUE TITLE
Remove toasts during guest --> user login

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#135]
When a user logs in (moving from guest status to user status), “added to list” toast pops up to alert that guest items are being added to the user’s account. 

Remove toasts and find a clearer way of telling the user that this is happening. (Especially awkward if the user has previous items in his/her list)

idea: start creating sublists within the recyclerview, marked w/ dividers

**Comment by mattl** [comment]
Moving this to 0.4 -- you were having some divider issues.

**Comment by perpetuatingcuriosity** [comment]
The toasts show up when they’re supposed to now. I think the sublists w/ dividers idea will be a 2.0 thing when we have more content.
