### ISSUE TITLE
Multiple duplicate images uploaded (v0.1, Android 5.0.1)

### ISSUE THREAD

**Issue by ryanmerkley** [creativecommons/list#137]
When uploading an image via the android app, I see multiple (4 per upload) copies of each image in "my images" list.

**Comment by mattl** [comment]
Can you try one via the web app?

**Comment by ryanmerkley** [comment]
Tried uploading via the webapp. Image uploaded. Sent for processing. Never
appeared in my images.

**Comment by mattl** [comment]
I believe this issue has gone away.
