### ISSUE TITLE
Upload image in background, add progress notification/confirmation to Android app drawer

### ISSUE THREAD

**Issue by ryanmerkley** [creativecommons/list#138]
Waiting for the image to upload holds up the user. When the user submits an image, we should move that process to the background, offer a progress notification in the app drawer, followed by a confirmation "image uploaded". Both the FB and Tumblr apps do this (for reference).

**Comment by perpetuatingcuriosity** [comment]
Closing! The way the app works now seems to handle this issue. I opened a new issue for the progress bar, which could use a little work: https://github.com/creativecommons/list/issues/188

@ryanmerkley Let me know if there’s something else I’m missing!
