### ISSUE TITLE
Create a "user menu"

### ISSUE THREAD

**Issue by ryanmerkley** [creativecommons/list#139]
We should create a user menu, to allow the user to navigate the app. We will need to work on nomenclature to differentiate between "my lists" (lists the user has created) and "my list items" (items from someone's list that I want to capture/submit). 

At a high level, the menu should include:

- Lists
   - Users can add items from other people's lists and create their own lists
   - Users can set their subject matter interests
- List items
   - Users can review items that they have said they want to photograph
   - Should also allow them to get to the add items menu
- My images
   - User can access a gallery of images they have uploaded 
- Photostream
   - Users can see a stream of images uploaded today via the List app. 
   - Users can rank quality of images (Alex had a version of this mocked up)
- App settings
   - Change app settings like attribution, ID
- About
   - See the other bug on this topic

Many apps on Android use a "swipe right" function to expose this as a side drawer, which I think is simple and clear. Could also use the "menu" icon that is becoming standard (three horizontal lines) as the indicator. Could replace the three dots in the top right, and add those items to that menu.

**Comment by mattl** [comment]
What's the standard on this with material design? We should that.

**Comment by ryanmerkley** [comment]
http://www.google.com/design/spec/material-design/introduction.html

**Comment by perpetuatingcuriosity** [comment]
Hey @ryanmerkley, all these features sound great! I’d love to start exploring these, but I’m thinking it might be best to hold off until phase two.

With just one month remaining we want to be careful not to bite off more than we can chew. We have a list of things we've been targeting for the MVP (see #145) and we want to complete those asap so that we can focus on polish and refinement.

**Comment by perpetuatingcuriosity** [comment]
Getting on it, this week! I’m thinking for now we can transfer what we have to this format:

- Your List (eventually toggle between your items (added) + items you’ve created #212)
- Gallery
- Create a List Item
- Pick Categories
- About The App
- Settings

**Comment by perpetuatingcuriosity** [comment]
Working on the nav-drawer branch.
