### ISSUE TITLE
The List App MVP Reference [notes]

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#145]
Hey just wanted to post some of my notes on where we are at the moment ahead of our meeting on Monday. Feel free to add to it if you feel anything is missing!
<br>

**The App Needs To:**
- Allow users to take and upload photos
- Allow users to view the items in their list
- Allow users to edit their list
- Make users want to use The List

**The User Needs To Be Able To:**
- Sign Up for a CCID within the app
- Choose the categories they want see list items from
- Re-upload a photo if an upload fails
- See photos that have been uploaded
- Express opinions about photos

**Endpoints We Need:**
- POST **/users/register**
  - create new user account
  - return user object including new session key
- PUT **/users/:userid/category/:categoryid** (Also see: #144)
  - save single user category preference based on ID
- DELETE /users/:userid/category/categoryid 
- GET **/users/:userid/category/** (Also see: #144)
  - return array of the category objects of categories the user has selected
- GET **/photos/random/:x**
  - return x number of random photos from a single list item
  - each photo object: URL, id, maker, user name, 
- POST **photos/:id/vote**
  - add one vote to the photo with matching ID
  - returns photo object with updated number of votes

**App Features In-Progress (my tasks):**
- Make user logins simple and as few as possible
- Delete an item reliably
- Make failed uploads easy to fix
- Make uploading photos feels like a rewarding experience
- Generally make sure any errors are handled gracefully/error messages should be helpful to the user
- Add helper text overlays for first-time users

**Other Tasks**:
- “About the App” section
- Google Analytics in TOS

**Comment by mattl** [comment]
Maciej -- if you could edit this with what we discussed on Friday, with agreed features for launch day.

**Comment by wchwd** [comment]
From Friday's meeting (Feb 20):

PRE-LAUNCH:
- category support (add/remove user categories; if logged-in, list item endpoints only return items matching a user's categories)
- item suggestion (user can suggest items to be added to the list, can include a photo along with suggestion)
- pseudo-progress bar (possibly in notifications bar like how flickr does it)
- rudimentary gallery / "my photos" view

POST-LAUNCH:
- latest photos feed
- ratings system
- share intent (i.e. so you can post to the list from any app)

**Comment by perpetuatingcuriosity** [comment]
Working with #308 now
