### ISSUE TITLE
Add a category to user profile

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#149]
**PUT /users/:userid/category/:categoryid** (Also see: #144)
- save single user category preference based on ID

**Comment by mattl** [comment]
Okay, so this is now:

POST /usercategories/add/userid/categoryid

What kind of a response do you want back?

**Comment by perpetuatingcuriosity** [comment]
Just a success: 204 should be fine for now.

**Comment by mattl** [comment]
Done
