### ISSUE TITLE
Include Google Analytics in TOS for first public beta 

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#152]
This is just the one liner about Google Analytics being built-in for this release.

**Comment by mattl** [comment]
Moving this to 0.4. @perpetuatingcuriosity -- there's a message which explains this for now, but it can't turned off until 0.4, right?

**Comment by sarahpearson** [comment]
Okay, so we don't need any additions to the TOS for this Friday's release then? Just confirming.

**Comment by perpetuatingcuriosity** [comment]
I think we wanted to add a one-liner to the current TOS about using Google Analytics stating:
- the beta release app has Google Analytics built-in to get data on how the app is being used but no personal info is collected (basically to help us build a better product)
- in future releases you will be able to opt out

Is this right, @mattl? Do we need to include a link to the Google Analytics TOS?

**Comment by sarahpearson** [comment]
Okay, got it. I will add something to the TOS. Thanks!

On Feb 24, 2015, at 9:48 AM, perpetuatingcuriosity <notifications@github.com>
wrote:

I think we wanted to add a one-liner to the current TOS about using Google
Analytics stating:

   - the beta release app has Google Analytics built-in to get data on how
   the app is being used but no personal info is collected (basically to help
   us build a better product)
   - in future releases you will be able to opt out

Is this right, @mattl <https://github.com/mattl>? Do we need to include a
link to the Google Analytics TOS?

—
Reply to this email directly or view it on GitHub
<https://github.com/creativecommons/list/issues/152#issuecomment-75781501>.

**Comment by mattl** [comment]
I'll move this back to Friday then.

**Comment by sarahpearson** [comment]
I added a sentence about data collection. I don't see any reason to name Google Analytics directly. 

I'll also discuss with Diane later today to make sure she signs off, and I'll close this issue once she does.
