### ISSUE TITLE
Categories and List Items for beta

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#155]
Hey we got a starter list of categories/items going–ideas for the beta! I thought I could post it up here to chat about it tomorrow. The goal was to pick items that wouldn’t be too difficult for people to find. 

Additions welcome!

**Categories**
- People
- Places/Cities
- Fashion/Clothing
- Nature/Animals
- Food

**People**
- Sitting on a bench
- Sipping coffee
- Crossing guard
- Under an umbrella
- Marathoner
- A gaggle of cyclists
- Laughing alone with salad
- Struggling to drink water
- Relaxing at the park
- Picnicking
- Line-up
- Love
- The lonely commuter
- Gone fishing
- Hanging out
- Family vacation
- Going to a concert 
- Business handshake
- Business person with megaphone

**Places/Cities**
- Skyscraper
- Downtown
- Uptown
- A house full of character 
- The storefront 
- Community centre
- Cafe
- The gym
- Elevator
- Theatre
- Construction site
- Abandoned building
- Graffiti
- Your favourite street corner

**Fashion/Clothing**
- Oxfords
- Hipster eyewear
- Bow tie 
- Three-piece suit
- Terrible Jeggings
- Colourful socks
- Cleats
- Evening gown
- New shoes
- Comfy old shoes
- Embarrasing clothing
- Something your grandmother would wear
- Tiny sneakers
- Warm scarf

**Nature/Animals**
- Forest
- a squirrel
- Bird in flight
- Cat
- Dog
- Rocky terrain
- Empty field
- Fish
- Sandy shores
- A body of water
- Snowflakes
- Fresh snow
- The weather
- Winter winds

**Food & Drink**
- Croissants
- Lunch Platters
- Wine
- Pizza shop
- An ordinary breakfast
- Cake
- Beer on tap
- The dinner table
- Your favourite meal
- Pancakes
- Bar Food
- Fancy Cheese
- Appetizers
- Lasagna
- Nourishing
- Cooking
- Soup from a can
- Anything homemade

**Comment by mattl** [comment]
If you can make the sql.txt file as discussed on Friday, I'll load it up into the DB.

**Comment by perpetuatingcuriosity** [comment]
Added!
