### ISSUE TITLE
app crashes after adding an item to my list

### ISSUE THREAD

**Issue by mattl** [creativecommons/list#167]
I added "fancy cheese" from the local zoo and the app stopped.

**Comment by mattl** [comment]
the app seems to be still running, weirdly.

**Comment by mattl** [comment]
yeah, it's happening after every thing i add.

**Comment by mattl** [comment]
still happening after the TLS reboot.

**Comment by perpetuatingcuriosity** [comment]
Figured it out. Oh, NullPointerException. We are BFFs.
