### ISSUE TITLE
"sorry there was an error" on photo upload

### ISSUE THREAD

**Issue by mattl** [creativecommons/list#168]
the item did eventually leave my list, and there was some progress bar.

and the photo is now in my images on the web app.

**Comment by perpetuatingcuriosity** [comment]
Is this still happening post-TLS reboot?

**Comment by mattl** [comment]
yep.

**Comment by mattl** [comment]
not seeing this now.

**Comment by mattl** [comment]
Seeing this again.

**Comment by perpetuatingcuriosity** [comment]
@mattl Let me know if this is still happening with the lastest fix.
