### ISSUE TITLE
Set minimum categories to 1 

### ISSUE THREAD

**Issue by amunizp** [creativecommons/list#184]
When. Choosing two categories nothing else happens.

**Comment by mattl** [comment]
Thanks for reporting this. I'm going to split this up into 2 bugs.

**Comment by mattl** [comment]
We think categories will become more like tags, so we're going to park this for now.

**Comment by perpetuatingcuriosity** [comment]
As of 0.4.1 the min will be 1. Once category filtering is in (#118), we’ll need to add some more items for each category.
