### ISSUE TITLE
Make progress bar less crazy/frenetic

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#188]
Two possibilities:

1) Use a determinate progress bar (fills up left to right)
2) Show the indeterminate progress bar (what we currently have) but for a very limited time

**Comment by ryanmerkley** [comment]
+1 to option 1.

**Comment by mattl** [comment]
+1 to #1

**Comment by perpetuatingcuriosity** [comment]
Put a time limit on the current bar. A true progress bar is doable, but involves rewriting how uploading a photo works. Thinking this might be more of a 2.0 thing. Closing this issue. Moved the determinate bar to #249

**Comment by mattl** [comment]
Not seeing any bar now.

**Comment by ryanmerkley** [comment]
Same for me.

**Comment by mattl** [comment]
Can confirm it's back in beta 4.
