### ISSUE TITLE
images are huge

### ISSUE THREAD

**Issue by xolotl** [creativecommons/list#190]
when listing images (eg, https://thelist.creativecommons.org/app/my-images.php) use a capability to resize them to something sensible so the page doesn't take forever to load

**Comment by mattl** [comment]
Yeah, these are the images in their raw, unprocessed state. When we upload them to the Internet Archive, we'll upload them in a couple of different sizes, including a scaled version.

**Comment by xolotl** [comment]
That sound good, especially if The List UX is also showing optimized
versions.

On Tuesday, March 10, 2015, Matt Lee <notifications@github.com> wrote:

> Yeah, these are the images in their raw, unprocessed state. When we upload
> them to the Internet Archive, we'll upload them in a couple of different
> sizes, including a scaled version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/list/issues/190#issuecomment-78075601>
> .
>


-- 
= Nate Angell
+1.503.927.1162 mobile
nate@xolotl.org email, chat
ixmati = skype
@xolotl <http://twitter.com/xolotl>
xolotl.org

**Comment by mattl** [comment]
#191 solves this.

**Comment by mattl** [comment]
We have much smaller images in the mobile app now. The web app will be updated later to accomodate this.
