### ISSUE TITLE
We’ll need thumbnail + mobile large sizes of users’ images for the gallery view

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#191]

**Comment by mattl** [comment]
So, as discussed, we'll append a size to the URL... I am working on the specifics now.

**Comment by perpetuatingcuriosity** [comment]
@mattl Right now I’m just getting the same shark image returned at the same size for both urls (appending /300 + appending /1024 to the original url)

**Comment by mattl** [comment]
Yep. Only generated 200px images right now. Other sizes to follow.

**Comment by perpetuatingcuriosity** [comment]
Cool! Works with the new urls. Detail view is shark-tastic.

**Comment by mattl** [comment]
Lets pivot on the app, just make an app about the shark.

**Comment by mattl** [comment]
@perpetuatingcuriosity can you confirm which sizes we want and I'll get them today.

**Comment by perpetuatingcuriosity** [comment]
@mattl  /200 and /1024?
