### ISSUE TITLE
finalize contributor agreement

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/list#195]
@mattl Could you review this new version and see if you have thoughts about logistics (and anything else in there)? Then I'll send to Diane for sign-off. Thanks! 

https://docs.google.com/a/creativecommons.org/document/d/1pVR9fXrujjjCoo6e0cUZCQriZXNLbbrZjwOasO7FAdQ/edit

**Comment by sarahpearson** [comment]
Matt has signed off, so it's ready for your sign-off @peterspdx. I believe Matt is hoping to have it for the next release on Monday if possible. Thanks! 

(apologies for not closing the loop here earlier! I had a brain lapse and did it via email on monday. :)

**Comment by peterspdx** [comment]
Reviewed, left two comments.

**Comment by sarahpearson** [comment]
Updated file in github. Should be good to go.
