### ISSUE TITLE
/api/photos/:userid should also return maker name, item name, item ID

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#196]
Right now only url for photo is being returned

We may want to add other values to this list when we talk about gallery functionality for 2.0

**Comment by perpetuatingcuriosity** [comment]
@mattl Is it possible to start returning the item name this week? Just a bit easier than testing with urls, and then the expanded view can include the item name in the action bar :)

**Comment by mattl** [comment]
I put in a fix for this, its returning more information than before.
