### ISSUE TITLE
Users should be able to add their own list items

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#205]
- need an activity to send this post request

**Comment by ryanmerkley** [comment]
What must a user do to add their own basic list item? What information do we want from them? Let's imagine this is being done on mobile for single items (we may want to develop a mass uploader system for later to allow something like "all wikipedia images" or "all national parks").

- Description (w/ character limit)
- Category (drop-down from our list of options)
- Sample image (upload/link option - could be a 2.0 feature)
- #hashtags?
- Creator notes (requestor info e.g., when we need it, what it's for, other directions to photographers)

Just brainstorming here. Let's refine for the MVP.

**Comment by ryanmerkley** [comment]
MVP:
- description w/ character limit so it displays properly on the "add list items" tool
- category (drop down from our list of 6 options)
- sample image (take / upload / link)

Thanks.

**Comment by perpetuatingcuriosity** [comment]
Hey matt, can you post an example for the add an list item endpoint here?

**Comment by mattl** [comment]
POST /api/suggestions 

userid, categoryid, description, filedata

Very similar to how photos are sent.
