### ISSUE TITLE
Get rid of or verify android library jars

### ISSUE THREAD

**Issue by mvdan** [creativecommons/list#209]
Concerning the jars found in `app/TheListApp/app/libs/*.jar`, I would suggest that you either:

* Replace the jars by maven dependencies from jcenter
* In a text file, document where they come from (including where their source code is) and their license to ease verification and reference

This is advisable for inclusion in F-Droid :)

**Comment by mattl** [comment]
Alex, now we're getting to the point where we're looking to get into various app stores, it would be good if we could use maven dependencies rather than having the jars in our repo. Do you think that'll be a problem?

**Comment by perpetuatingcuriosity** [comment]
No problem :dancer:

**Comment by mvdan** [comment]
That was fast :)

**Comment by mattl** [comment]
http://paste.cat/b73377e1

**Comment by perpetuatingcuriosity** [comment]
Fixed! Funnily enough, it had nothing to do with the new dependencies I added. Thanks proguard.

**Comment by mattl** [comment]
Thoguard.
