### ISSUE TITLE
Toggle between your list items and the items you’ve created from the main feed

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#212]
Example below: Google’s Inbox app! Instead of pinned items, think maker items. 

![screen shot 2015-03-30 at 2 08 03 pm](https://cloud.githubusercontent.com/assets/6563209/6903130/3ae6c1c4-d6e6-11e4-9737-40fe544b4308.png)
![screen shot 2015-03-30 at 2 08 10 pm](https://cloud.githubusercontent.com/assets/6563209/6903131/3bfb8f4a-d6e6-11e4-92c4-539af2d30d71.png)

The Floating Action Button (plus button in the corner) will represent “add an item” in both “pinned” and “non-pinned” view.

**Comment by mattl** [comment]
I think this is 2.0

**Comment by perpetuatingcuriosity** [comment]
With the design updates #308, this is no longer relevant.
