### ISSUE TITLE
create new TOS for 1.0 release 

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/list#213]

**Comment by sarahpearson** [comment]
@mattl Here is a draft of terms for 1.0. Can you take a quick look? Just want to make sure I have the facts straight about what we will be doing with images, etc. Then I'll send to Diane for sign-off. 

https://docs.google.com/a/creativecommons.org/document/d/1b7lCFnEsnC3PGBRyZ4U_dVMrv1dFgF8uQtf4C53cVAs/edit

**Comment by mattl** [comment]
Looks good. 5 bags of popcorn.

**Comment by sarahpearson** [comment]
Assigning this to @peterspdx for her sign-off.

**Comment by peterspdx** [comment]
Good here.

**Comment by sarahpearson** [comment]
Posted the file in the docs folder. Hope that was the right place @mattl!
