### ISSUE TITLE
When I add to my gallery, I see sharks for my recent uploads (“image not found”) 

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#214]
The last 3 images I uploaded (userid: 2) still haven’t loaded. It’s been 5–10 minutes maybe? The placeholder shark didn’t appear for around 2 mins (have we solved #174?)

I can see them in the response: https://thelist.creativecommons.org/api/photos/2
But I’m guessing the smaller sizes haven’t been generated yet? Not sure if something is up here.

**Comment by janeatcc** [comment]
Same here. It's been ten min and sharks still show up.

**Comment by tarkowski** [comment]
same here, shark still there, a day after uploading

**Comment by mattl** [comment]
Can you all look again? I think the cronjob wasn't running, so no images were being processed. They should be processed within 90 seconds of being posted now.

**Comment by mattl** [comment]
@perpetuatingcuriosity how long are you caching the gallery results in app?

**Comment by perpetuatingcuriosity** [comment]
@mattl: So it looks like the library loading in the images is doing the caching. Because the urls are exactly the same, it doesn’t reload the image when it switches from a placeholder shark to a valid image. 

To save bandwidth, can the API return a separate url until all images sizes have been generated? 

e.g.: 
```{url": "https://thelist.creativecommons.org//live/image-not-found-shark.jpg"}```

**Comment by janeatcc** [comment]
No sharks now for photos I uploaded on Fri. However photo I just uploaded
showed a camera placeholder icon and then disappeared entirely.

On Mon, Apr 6, 2015 at 11:00 AM, perpetuatingcuriosity <
notifications@github.com> wrote:

> @mattl <https://github.com/mattl>: So it looks like the library loading
> in the images is doing the caching. Because the urls are exactly the same,
> it doesn’t reload the image when it switches from a placeholder shark to a
> valid image.
>
> To save bandwidth, can the API return a separate url until all images
> sizes have been generated?
>
> e.g.:
> {url": "
> https://thelist.creativecommons.org//live/image-not-found-shark.jpg"}
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/list/issues/214#issuecomment-90176510>
> .
>



-- 
Jane Park
@janedaily
Creative Commons | Los Angeles

Make a donation to support CC in 2015: http://bit.ly/supportcc2015

**Comment by mattl** [comment]
@perpetuatingcuriosity https://github.com/creativecommons/list/commit/5ede763c2c0df6413815793e18658f5ca07ce406 fixes this.

**Comment by perpetuatingcuriosity** [comment]
Cool. I’m not seeing sharks at all, but it does update to the uploaded image eventually. Will keep testing this periodically.

**Comment by perpetuatingcuriosity** [comment]
Seems like this is working now.
