### ISSUE TITLE
Login screen doesn't show password field when typing

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/list#215]
Keyboard covers over password field when typing. Shows only email field.

**Comment by perpetuatingcuriosity** [comment]
Hey @janeatcc, what device are you using?

**Comment by mattl** [comment]
Almost everyone at CC is using LG REALM LS620

**Comment by janeatcc** [comment]
Yeah that's what I'm using.

On Mon, Apr 6, 2015 at 8:33 AM, Matt Lee <notifications@github.com> wrote:

> Almost everyone at CC is using LG REALM LS620
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/list/issues/215#issuecomment-90109133>
> .
>



-- 
Jane Park
@janedaily
Creative Commons | Los Angeles

Make a donation to support CC in 2015: http://bit.ly/supportcc2015

**Comment by sarahpearson** [comment]
Yes! I thought this was just me. It made it really hard to log in.

**Comment by perpetuatingcuriosity** [comment]
fixed
