### ISSUE TITLE
Category checkmark is big and blurry

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/list#218]
The checkmark when selecting categories is big, blurry and ugly

**Comment by mattl** [comment]
Can you provide a screenshot? On your Android phone, pressing the down volume rocker and the power button at the same time should take a screenshot.

**Comment by janeatcc** [comment]
![the list sn](https://cloud.githubusercontent.com/assets/6394777/7010204/4ced8f74-dc54-11e4-8a8e-f4a9bb85f993.png)

**Comment by perpetuatingcuriosity** [comment]
Images now fade when selected. No checkmark. If we have time, it would be cool to add another visual indicator that a category has been selected.
