### ISSUE TITLE
CC logo on splash screen is pixellated

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/list#220]
It looks pixelated.. not the highest res.

**Comment by mattl** [comment]
Can you provide a screenshot or at least some more detail here?

**Comment by janeatcc** [comment]
When you're loading the app for the first time, there's a screen that pops
up with just the (cc) logo -
http://mirrors.creativecommons.org/presskit/icons/cc.large.png. This logo
looks a little rough around the edges, like it could be higher resolution,
at least on my screen. Too quick to catch but I can try again when I have
the phone on wifi.

On Mon, Apr 6, 2015 at 8:07 AM, Matt Lee <notifications@github.com> wrote:

> Can you provide a screenshot or at least some more detail here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/list/issues/220#issuecomment-90095057>
> .
>



-- 
Jane Park
@janedaily
Creative Commons | Los Angeles

Make a donation to support CC in 2015: http://bit.ly/supportcc2015

**Comment by janeatcc** [comment]
Tried again just now but it goes by too quick for me to screenshot b/c the LG is slow and requires you to click save even after you hold down the two side buttons. If you can make it higher res, good, if not, no big I thnk.

**Comment by mattl** [comment]
I don't think the image is being displayed bigger than it should be, I'll
double check on this.

**Comment by perpetuatingcuriosity** [comment]
Probably need the right image size for that screen density: http://developer.android.com/design/style/iconography.html

Right now there is only 1 image for all screens.

**Comment by perpetuatingcuriosity** [comment]
drawables updated!
