### ISSUE TITLE
picture do not go to gallery

### ISSUE THREAD

**Issue by amunizp** [creativecommons/list#222]
V0.8 for android on moto g installed today. Tried with default camera and f-droid stick camera
Added item(s) to list.
Press done.
Selected item. 
Camera app loaded.
Took picture.
Accepted.
Notification
Menu (...)
My photos
All have shark image not found.
Tap on notification sends me to list not gallery.
Tap in notification does not delete notification.

Unsure if any of the above us meant yo be.

**Comment by amunizp** [comment]
*above is meant to be.

**Comment by mattl** [comment]
Thanks for your report! 

I see three bugs here, so I'll make them now.

**Comment by mattl** [comment]
I think #214 fixes the shark issue. I'll mark this issue as closed now.
