### ISSUE TITLE
Add CC branding in the app

### ISSUE THREAD

**Issue by ryanmerkley** [creativecommons/list#223]
There are a few key areas where the app should be more clearly branded. Here are a few:

- Display CC logo and The List on launch (I think it always does this, but not sure)
- Add CC logo beside The List on the list menu
- Add CC | The List to the list item selection pages

**Comment by perpetuatingcuriosity** [comment]
Added the CC logo to the nav drawer.

**Comment by perpetuatingcuriosity** [comment]
@ryanmerkley Does the current version solve this issue?

Currently:
- logo is displayed on launch of the app (whether you are logged in or not)
- logo is visible every time you open the app drawer

I think the CC logo on the list item selection screen will be a bit much. It’s meant to be a screen with quick yes/no interactions and the more visual elements on that page, the more the user has to digest before making a decision.

**Comment by perpetuatingcuriosity** [comment]
Going to close this. If there’s anything specific that needs further adjusting, let me know in a new issue :)
