### ISSUE TITLE
Add some gratitude features to the app

### ISSUE THREAD

**Issue by ryanmerkley** [creativecommons/list#224]
Add some features to the app that make users feel appreciated for their contribution, and connect their submission to the larger cause of building a global commons. 

Ideas:
- After 5th submission, get a message that says "You've submitted 5 photos to the commons. Thank you!"
- On successful upload: "Your image has been uploaded. The Commons is one image better. Thanks."

These are just ideas, but you get the point.

**Comment by perpetuatingcuriosity** [comment]
Might be useful to have a user profile endpoint now. So I we can start tracking number of submissions. Then we can display this to the user (like in the app drawer) and also send messages at whatever key points we decide :)

**Comment by perpetuatingcuriosity** [comment]
**Update to this post May 4 Meeting:**

For 3.0, we’ll release messages for uploading 5, 10, 15, 20, 25 photos.

**Comment by mattl** [comment]
For 100 photos, we should bring the shark back.

**Comment by perpetuatingcuriosity** [comment]
App sends a random congratulatory message based on no. of photo uploads.
