### ISSUE TITLE
Tap on notification sends me to list not gallery.

### ISSUE THREAD

**Issue by mattl** [creativecommons/list#227]
As reported by @amunizp

When you upload a picture, tapping the notification sends you to the list, not the gallery.

**Comment by perpetuatingcuriosity** [comment]
Because the images take a while to be processed, maybe we should leave this for 2.0? Users might find it more frustrating to be directed to the gallery and find their image missing.

**Comment by mattl** [comment]
Now that the shark is present, and should be returning a 404, it would be possible for you to indicate this in some way, but yes, version 2.

**Comment by perpetuatingcuriosity** [comment]
Getting rid of notifications for uploads (discussed in #266)
