### ISSUE TITLE
api/userlist/:userid/:itemid inconsistently adding items

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#238]
I’m getting a 200 response, but items are often not being added to my list.

If multiple items are added, often only the first is added. If I add only one item, sometimes it doesn’t add at all. 

Any ideas @mattl? Trying to figure out if it might be on my end, but I’m receiving a response for everything I add.

**Comment by mattl** [comment]
Can you reproduce with curl?

**Comment by perpetuatingcuriosity** [comment]
Ok, so we figured out this is likely because I had already uploaded images for all the items. Closing this in favour of #239
