### ISSUE TITLE
Pick Categories Layout Resizing

### ISSUE THREAD

**Issue by robmyers** [creativecommons/list#241]
Android 5.1 Nexus 6
03_30_15 version.

When I select a category on the Pick Categoreis screen, the addition of the tick resizes the coloured block, making it larger and pushing any content below it further down the screen.

When I deselect a category, the coloured block returns to its original size.

If two horizontally adjacent categories are in different states the coloured block for the unselected one has a light grey area below it.

**Comment by perpetuatingcuriosity** [comment]
Layout adjustments made!
