### ISSUE TITLE
The List Screen Item Highlighting

### ISSUE THREAD

**Issue by robmyers** [creativecommons/list#244]
Android 5.1 Nexus 6
03_30_15 version.

On the main "The List" screen with the list of accepted requests for images, is it possible to highlight the most recently selected item within a session?

This is so the user can easily find it on returning from cancelling taking a photograph by pressing the X button in the camera view screen.

It provides the user with some context, and if they cancelled by mistake it makes it easier to find the item and return to the camera screen.

**Comment by perpetuatingcuriosity** [comment]
Not being able to find an item will definitely be an issue with larger lists. #225 (sorting items) should deal with this.
