### ISSUE TITLE
Add additional upload confirmation dialogue

### ISSUE THREAD

**Issue by guerda** [creativecommons/list#245]
If you select an image from the gallery, or will be immediately be uploaded without the chance to abort the upload. It would be great to have an additional upload dialogue in which you have to confirm if that is the photo you want to upload.
This prevents erroneous uploads.

**Comment by perpetuatingcuriosity** [comment]
Yeah definitely! #266 deals with new design that can accommodate this.

**Comment by perpetuatingcuriosity** [comment]
In 4.0, dialog confirming that your content is original provides additional opportunity to cancel. 

We can #266 to discuss if any further changes are necessary :)
