### ISSUE TITLE
Item picker screen lowercases the item string

### ISSUE THREAD

**Issue by mattl** [creativecommons/list#251]
so "matt lee" appears here, but "Matt Lee" appears on my list.

**Comment by perpetuatingcuriosity** [comment]
Every word that started with an “A” was capitalized and it was throwing off the visual flow sentence.

E.g.:
“Matt needs a picture of A cake”

So everything that comes in from the API was converted to lowercase. The issue is that capitalizing every word is also visually jarring:

“Matt Needs
