### ISSUE TITLE
Write a blog post about 1.0

### ISSUE THREAD

**Issue by mattl** [creativecommons/list#256]

**Comment by ryanmerkley** [comment]
Matt, I'd like to work on this one with you. Let's plan to post it early
next week after demo day.

**Comment by mattl** [comment]
Does this mean we're not releasing 1.0 on the website until after demo day? :)

**Comment by mattl** [comment]
Here's the previous blog post: https://thelist.creativecommons.org/android/2015/03/31/0.8-is-ready.html

**Comment by ryanmerkley** [comment]
No, just means we don't post blog until then. I'd like to talk about why we
built the app, and what's next now that we're done the prototype. And thank
partners, etc.

**Comment by mattl** [comment]
Do you have other key points you want to hit? I can work on a draft
