### ISSUE TITLE
New users don't get the initial splash screen with a "i'm new to the list" option or the ability to pick categories

### ISSUE THREAD

**Issue by mattl** [creativecommons/list#261]

**Comment by perpetuatingcuriosity** [comment]
@mattl: Not sure if I’m understanding the issue with “pick categories”.

Every time I’ve selected “I’m new to the list” I get the option to pick categories after I read through the helper screens that explain how the app works.

**Comment by mattl** [comment]
The screen with that button on it doesn't appear to a new user. Just get
dumped right into an empty list.

**Comment by perpetuatingcuriosity** [comment]
Which button?

**Comment by mattl** [comment]
"I'm new to the list"

That whole screen never appears the first run of the app.

**Comment by perpetuatingcuriosity** [comment]
How is this different from: #260?

If you’re a new user and you add items to your list, leave the app and come back, your items added will be remembered. You’re only asked to login when you try to upload an item; it might be frustrating to lose your items every time you leave the app if you’re just trying it out for the first time. 

Haven’t been able to replicate the app opening to an empty list.

**Comment by perpetuatingcuriosity** [comment]
@mattl are you talking about not being able to pick items?

**Comment by mattl** [comment]
Install the app for the first time, open it, goes straight to The List/My
List screen with no items.

**Comment by perpetuatingcuriosity** [comment]
Looks like it’s fixed with #260. Will leave this here to confirm with next debug release

**Comment by perpetuatingcuriosity** [comment]
K looks good. Reopen if you find this happening still :)
