### ISSUE TITLE
Remove right-side menu

### ISSUE THREAD

**Issue by ryanmerkley** [creativecommons/list#263]
"About the app" appears both in the user menu and in the right hand side menu. Remove it from the right hand side menu.

**Comment by mattl** [comment]
Updating this: please remove the right hand menu completely.

**Comment by perpetuatingcuriosity** [comment]
@mattl Do you want a version with “Debug Accounts” for yourself?

**Comment by mattl** [comment]
No, for now let's remove that completely. You can always uninstall the app.
