### ISSUE TITLE
Swipe away on a list item should indicate what happens after swipe and offer undo

### ISSUE THREAD

**Issue by ryanmerkley** [creativecommons/list#265]
A left or right swipe removes the item from the list. Before the item is removed, it should indicate that it has been removed, and have an option to undo.

**Comment by mattl** [comment]
There should be an undo at the bottom of the screen, but I agree we might need to indicate what happens.

**Comment by mattl** [comment]
This is what you call the snackbar, I think.

**Comment by mattl** [comment]
Let's do what Gmail and others do. Show you an icon/text under the item...

**Comment by ryanmerkley** [comment]
Just checked: If your list is long than the screen, the undo doesn't appear.

**Comment by janeatcc** [comment]
So a swipe down "undoes" the delete -- is that intentional?

**Comment by perpetuatingcuriosity** [comment]
Fixed
