### ISSUE TITLE
App should indicate "your photo will be uploaded" and "item has been removed from your list"

### ISSUE THREAD

**Issue by ryanmerkley** [creativecommons/list#266]
When the user selects an image to upload, and taps the checkmark, they are returned to their list, the uploader progress bar starts, and the item is removed from their list. 

The app should tell the user "Your image will be uploaded, and the item has been removed from your list".

**Comment by mattl** [comment]
I think we had a toast that did this, maybe we hid it?

**Comment by perpetuatingcuriosity** [comment]
If we add in two more layers of notifications for 1.0, will the user feel overloaded with visual information?  Right now we have: a progress bar, notifications, and a snackbar.

I think we could handle this a bit better with future releases by redesigning the upload bar: 

![screen shot 2015-04-16 at 3 38 45 pm](https://cloud.githubusercontent.com/assets/6563209/7189711/b7c325dc-e44e-11e4-991f-23b25543c797.png)

**Comment by ryanmerkley** [comment]
What is the snack bar?

**Comment by perpetuatingcuriosity** [comment]
The little notification at the bottom of the screen. It’s used for short messages and actions.
![screen shot 2015-04-16 at 6 01 42 pm](https://cloud.githubusercontent.com/assets/6563209/7192369/c331fd12-e462-11e4-8371-6fe0e5ed58cb.png)

**Comment by ryanmerkley** [comment]
Gotcha. I don't have strong feelings about how we indicate. But it feels
odd that I press the upload button and nothing happens. I notice in the app
drawer seems like too much.

R.

**Comment by perpetuatingcuriosity** [comment]
Cool, yeah I agree the notifications are probably more than we need. I’m thinking: Let’s plan to have the example image (“uploading soup”) in 2.0, rather than adding a fourth way of notifying the user in 1.0. @ryanmerkley @mattl Does that work?

**Comment by ryanmerkley** [comment]
Ok

**Comment by ryanmerkley** [comment]
Alex, I like the idea of an "list item uploading" notification that sits on the "my list items" page at the top, with its own progress progress bar, as you sketched above. Very nice.

**Comment by perpetuatingcuriosity** [comment]
There is snackbar confirmation when a photo has been uploaded. Any additional between starting and upload and finishing are probably unnecessary because uploads don’t take very long. 

There is also now a progress bar in the phone Notifications.
