### ISSUE TITLE
Convert Category List and About the App to fragments (so they adhere to the hamburger menu format)

### ISSUE THREAD

**Issue by ryanmerkley** [creativecommons/list#267]
Hamburger menu appears on "my list" and "my photos" pages, "My categories" requires the user to use the back button, and "request an item" and "about the app" have a back arrow. 

Let's be consistent and use the hamburger menu for all of them.

**Comment by mattl** [comment]
not 100% sure, but i think this might be the Google recommended way to do it.

**Comment by perpetuatingcuriosity** [comment]
Hey so this may be a bit time consuming to get into 1.0, because it involves reformatting that entire screen. If there’s time, I can work on adding a back arrow on the category screen for consistency, but for the most part I’d recommend 2.0.

**Comment by mattl** [comment]
2.0 is also about 9 working days after demo day, so it's not like a lot of these 2.0 things are being pushed into the Laterbase...

**Comment by ryanmerkley** [comment]
This doesn't need to be in 1.0, but should be high on the list post-demo
day.

**Comment by perpetuatingcuriosity** [comment]
Right now: My Categories, About the App, and Request an Item are “non-hamburgers”

I’m renaming this issue so both My Categories and About the App get converted. 

It’s probably better to leave Request an Item for now, because for #212 Request an Item will need to be an activity.

**Comment by perpetuatingcuriosity** [comment]
With the new design #308, these can stay as they are.
