### ISSUE TITLE
Nomenclature

### ISSUE THREAD

**Issue by elliotharmon** [creativecommons/list#27]
Hi everyone,

Sorry if I'm retreading old ground here. I think it would be useful to have a single place where we keep track of the nomenclature we're using. I'd be happy to start it, but I need some help.

For example: looking on the demo, I see the phrase "added to the list." Are "the list" (lowercase) and "my picks" synonymous? That introduces a potential area of confusion, if we're using the word "list" to describe both the users' picks and the wishlists provided by listmakers.

**Comment by mattl** [comment]
I think we're mostly on the same page about this.

The List -- the big list of things.
User Lists -- personal selections from the master list
List Makers -- orgs which have added to the list
Users -- people who take photos and contribute suggestions for additional items
