### ISSUE TITLE
App drawer is laggy to open

### ISSUE THREAD

**Issue by mattl** [creativecommons/list#270]
Seems slow to open on my 5

**Comment by perpetuatingcuriosity** [comment]
@mattl Do you mean it’s slow to slide open, or that when you click an item it takes a long time to load the new screen?

**Comment by mattl** [comment]
Slow to slide open. It feels like it's "loading" the background image or
something.

**Comment by perpetuatingcuriosity** [comment]
Drawables for multiple screen sizes seems to have helped.
