### ISSUE TITLE
Notifications in app drawer are cut off

### ISSUE THREAD

**Issue by ryanmerkley** [creativecommons/list#271]
Saw a notification about my image failing to load. The full notification was cut off in the app drawer, and clicking on it just takes me to the List page - no information. Notifications should either display the full notification, or clicking them should take me to the notification full version in the app.

**Comment by perpetuatingcuriosity** [comment]
In #266 we discussed removing notifications altogether. We might not get to the new design in 2.0, but I can remove the notifications for now.
