### ISSUE TITLE
Store offline/local copy of list, images, etc on device

### ISSUE THREAD

**Issue by ryanmerkley** [creativecommons/list#275]
If connectivity is poor or unavailable, the app will not show my list items, gallery items, and simply load forever. It should have a local copy that it displays, and tell the user it is synching/updating.

**Comment by perpetuatingcuriosity** [comment]
Now storing an offline copy of your list items. Photos are a bit more difficult to integrate; thinking we should talk about this.

**Comment by ryanmerkley** [comment]
All the data items should be archived locally, and refresh. I get why pics
might not be ideal for that. We can discuss.

**Comment by perpetuatingcuriosity** [comment]
@ryanmerkley Offline list item are there, will close this for now and we can discuss at the design session? We can open a specific issues targeting photos if we need to at that point.
