### ISSUE TITLE
App crashes when saving new photo

### ISSUE THREAD

**Issue by ModernReplica** [creativecommons/list#276]
I opened the List (v. 1.0), selected option from My List (a photo of an umbrella).
I took the photo, and when given the choice to Save or Discard, chose Save.
The List app notified me it had crashed.

This happened twice, exactly the same experience each time. 

I tried this with another item from My List (cup of coffee), and had the same result, for 3x total.

Device: 
Samsung GT-I9100m (Galaxy S II)
Android v. 4.1.3

**Comment by mattl** [comment]
Stack trace:

STACK_TRACE = java.lang.NullPointerException
        at org.creativecommons.thelist.fragments.n.L(MyListFragment.java:789)
        at org.creativecommons.thelist.fragments.s.a(MyListFragment.java:750)
        at org.creativecommons.thelist.utils.o.run(ListUser.java:223)
        at android.accounts.AccountManager$10.run(AccountManager.java:1264)
        at android.os.Handler.handleCallback(Handler.java:605)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4514)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
        at dalvik.system.NativeStart.main(Native Method)

APP_VERSION_NAME = 1.0
BUILD = BOARD=smdk4210
BOOTLOADER=unknown
BRAND=samsung
CPU_ABI=armeabi-v7a
CPU_ABI2=armeabi
DEVICE=GT-I9100M
DISPLAY=IML74K.UGLD3
FINGERPRINT=samsung/GT-I9100M/GT-I9100M:4.0.3/IML74K/UGLD3:user/release-keys
HARDWARE=smdk4210
HOST=SEP-74
ID=IML74K
IS_DEBUGGABLE=false
MANUFACTURER=samsung
MODEL=GT-I9100M
PRODUCT=GT-I9100M
RADIO=unknown
SERIAL=unknown
TAGS=release-keys
TIME=1334817558000
TYPE=user
UNKNOWN=unknown
USER=se.infra
VERSION.BASEBAND=unknown
VERSION.CODENAME=REL
VERSION.HW_VERSION=unknown
VERSION.INCREMENTAL=UGLD3
VERSION.RELEASE=4.0.3
VERSION.RESOURCES_SDK_INT=15
VERSION.SDK=15
VERSION.SDK_INT=15
VERSION.SW_VERSION=I9100MUGLD3

PACKAGE_NAME = org.creativecommons.thelist
ANDROID_VERSION = 4.0.3
REPORT_ID = e303eff6-dd0e-4cb8-91be-1f3549bd170f
APP_VERSION_CODE = 2

**Comment by perpetuatingcuriosity** [comment]
The closest I could find was an emulated S2 4.1.1. Seems to be working fine when I logged in to my account. It looks like an issue with account manager; no authtoken was received. 

@ModernReplica When did you create your account? And have you changed your password since creating the account?

**Comment by mattl** [comment]
The stack trace reveals Android 4.0.3, btw.

**Comment by ModernReplica** [comment]
Hi Matt,

I had the previous two apps installed previously (when a new one came out,
I'd delete the first one, and install the fresh one).

I downloaded and installed 1.0 a few days after the announcement, and
created a new password. I can't recall if it was a new account (as in both
email and password were new).

I can set up a new account with fresh email and password and delete and
reinstall 1.0 as a test if that would help.

:)

**Comment by perpetuatingcuriosity** [comment]
@mattl Nice catch. I tried with API level 15  and it worked as welI. From what I’m seeing in the stacktrace, it sounds like it could be a few things:
- a token was never received and/or stored
- the userid was invalid (since the db reset everything, sharedPreferences and the db might no longer match)
- a password was invalid

@ModernReplica, did you create a new password before logging into 1.0 for the first time? Can you try deleting the app and reinstalling, then logging in with the account you have now and uploading?

**Comment by perpetuatingcuriosity** [comment]
I suspect this will resolve with #293. Moving this to 3.0
