### ISSUE TITLE
App defaults to My List page, cannot access other menu items.

### ISSUE THREAD

**Issue by ModernReplica** [creativecommons/list#277]
I set up the List App a few days ago (I selected 10 items for my list).

When I open the List App, it briefly displays a loading screen with 'My List' at the top, and immediately defaults to my list of ten items. I cannot access any other menu items.

I tried swiping side to side, using the phone/device Menu button, and swiping downwards in order to get access to the menus. I also tried to select the My List menu (green bar at top, when it was visible for two seconds).

Device: 
Samsung GT-I9100m (Galaxy S II)
Android v. 4.1.3

**Comment by ModernReplica** [comment]
![04-18-13-39-20- load screen](https://cloud.githubusercontent.com/assets/12011606/7217229/289f6d46-e5d1-11e4-86a0-d5d5c0da258d.png)
![thelist - 04-18-13-33-48 my list](https://cloud.githubusercontent.com/assets/12011606/7217231/2fcca246-e5d1-11e4-8476-dab0973f4966.png)

**Comment by perpetuatingcuriosity** [comment]
fixed!
