### ISSUE TITLE
Link to the TOS on About App page should go to latest version 

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/list#286]
Right now it goes to the alpha TOS

**Comment by perpetuatingcuriosity** [comment]
@mattl Where can I find the latest version? On The List site, I could only find: https://creativecommons.org/terms

**Comment by sarahpearson** [comment]
@perpetuatingcuriosity They are here: https://github.com/creativecommons/list/blob/master/docs/beta-TOS.md

**Comment by perpetuatingcuriosity** [comment]
Cool! Linking to this for now. When it’s up on the site (#289) I’ll switch the url again.
