### ISSUE TITLE
no image preview in my gallery in 1.0 version

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/list#287]
I have to click on the image to actually see the image. Otherwise, I just see a grey camera icon on the thumbnail. (This is about 20 minutes after I uploaded the image).

**Comment by perpetuatingcuriosity** [comment]
Hmm, odd. Can you double-check that this is 1.0? I’m looking at the resources for 1.0 on github and the “loading” placeholder image in the gallery should be three horizontal dots. There shouldn’t be any more camera icons.

**Comment by perpetuatingcuriosity** [comment]
@sarahpearson Is this still happening? If not, we can close this? :dancer:

**Comment by sarahpearson** [comment]
I'm away at a conference without my Android phone. I'll check when I return and let you know!
