### ISSUE TITLE
Get beta-tos up on thelist.creativecommons.org

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#289]
alpha-tos is at: thelist.creativecommons.org/alpha-tos.html

Can we get a ../beta-tos.html? :dancer:

**Comment by perpetuatingcuriosity** [comment]
@mattl Is this the correct url for The List terms? https://creativecommons.org/terms

It’s the only one I could find on the site. Getting “not found” for: helist.creativecommons.org/alpha-tos.html and helist.creativecommons.org/beta-tos.html

**Comment by mattl** [comment]
We won't keep it on the website, it's better in GitHub
