### ISSUE TITLE
give users a prompt about what happens with photos when they upload

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/list#291]
This should happen at least at time of first upload, and possibly others as well. Warning should explain that photos are licensed CC BY and available to the public for any use, etc.

**Comment by mattl** [comment]
Do we have the legal stuff to show them? I wonder if this is somehow related to @perpetuatingcuriosity and gratitude? Maybe we should be smart about this and at the point of upload know how many photos the user has uploaded? Also, will our TOS ever change down the line, possibly... right? I'm thinking this could be a very smart piece of code which checks a few things.

**Comment by sarahpearson** [comment]
@mattl what is timing on this ticket? Am I going to hold things up if I don't get to it until this weekend?

**Comment by mattl** [comment]
Nope:)

**Comment by sarahpearson** [comment]
Sharing my ideas via email. Let's discuss on the call Tuesday.

**Comment by perpetuatingcuriosity** [comment]
Right now we have a dialog with the same text for both “Take Photo” and “Choose Photo”. I know we talked about distinguishing the text for taking a photo vs choosing a photo. @sarahpearson What were you thinking for this? 

What we have now (below) may be a little long.

![screenshot_2015-05-27-16-03-46](https://cloud.githubusercontent.com/assets/6563209/7846287/9ee47460-048a-11e5-9199-a2e3806de3a7.png)

**Comment by sarahpearson** [comment]
I was imagining the "Only choose photos created by you!" text to show up only for the "Choose Photo" option, right before the person actually selects a photo. Then the other text could show up for both options right before upload. If we want to trim that longer text, we could delete the first sentence. ("The List only accepts...")
