### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by orschiro** [creativecommons/list#302]
Hi all, 

I tried to log into the Android app using my email and password. 

Both are valid when logging in at: https://login.creativecommons.org/login

However, the app tells me that they are invalid:

> Please make sure you enter a valid name and password.

Does someone experience the same issue?

Thankfully,

Robert

**Comment by egon0** [comment]
same here. i have set up an account via browser with an email xyz+creativecommons@domain.com, login on browser works, the app gives
> Please make sure you enter a valid name and password.

**Comment by mattl** [comment]
We've released a new version of the app, which you can get from https://github.com/creativecommons/list/releases -- can you confirm it's still a problem?

**Comment by orschiro** [comment]
@mattl 

It does work. Thank you very much! :)
