### ISSUE TITLE
Include a overlay for first-time users explaining how adding items works in RandomActivity

### ISSUE THREAD

**Issue by robmyers** [creativecommons/list#306]
List: 4.0 debug

Android: 5.1.1, Nexus 6

This is a design question.

When I have selected the categories I am interested in on the "My Categories" page, I am then shown an image requests, e.g. "Creative commons needs a picture of a hot dog cart".

When I agree to provide the picture (by selecting the check mark), I am shown another request rather than e.g. a message saying "OK, let's go get a picture of that hot dog cart!"

Is it worth framing or phrasing the image requests as future rather than immediate tasks so the user understands that this is another step in the initial configuration rather than thinking they've done something wrong because they're not being dropped into a picture-taking mode when they (apparently) agree to take a picture?

**Comment by perpetuatingcuriosity** [comment]
Hey rob, possibly the first time we show that suggestions screen, we could have an overlayed explanation of what this screen is about, something to the effect of: 

“Pick some items you’d be interested in contributing photos to” 

Similar idea to how google does it here: http://i.stack.imgur.com/3YhJAl.png

**Comment by robmyers** [comment]
Yes that sounds good. It's one of those things that makes perfect sense once you've done it, but where a little encouragement will help people get there without wondering if they're doing it right. :-)
