### ISSUE TITLE
"My images" for an anonymous user is unhelpful

### ISSUE THREAD

**Issue by mattl** [creativecommons/list#311]
http://imgur.com/pMtoqMB

Should have a way to sign up, login, etc

**Comment by AyoPrez** [comment]
But, even the anonymous user could want to see the pictures he has taken. Or the anonymous user take pictures and they go directly to the server?:/

**Comment by mattl** [comment]
Anonymous users can't upload images, because we don't know who they are and can't attribute to them.

**Comment by AyoPrez** [comment]
Then, the anonymous user only can make request? Ok :)

**Comment by mattl** [comment]
No, anonymous users can't make requests either, maybe that should be changed but not for now.

**Comment by AyoPrez** [comment]
Then, what do the anonymous user with the app?

**Comment by mattl** [comment]
They can make a list of images right now. We want to expand this, but
that's off-topic for this bug.

**Comment by AyoPrez** [comment]
:+1:

**Comment by perpetuatingcuriosity** [comment]
@mattl Thinking we should push this forward. Login is accessible from the nav drawer for anonymous users. If we’re releasing tomorrow, it’s a bit tight to debug properly.

**Comment by mattl** [comment]
I'd rather make this a little better (or just hide it from the menu entirely if they're anon) before a new release. 

How hard is it to hide it, or just change the page to have a link to sign in/register?
