### ISSUE TITLE
Remove the link to the survey from the menu

### ISSUE THREAD

**Issue by mattl** [creativecommons/list#313]
It's very out of date and we should build a new survey for future versions

**Comment by perpetuatingcuriosity** [comment]
The survey also pops up in a dialog when the user uploads a certain number of photos. Is it possible to just update the survey or is this feature on hold?

**Comment by mattl** [comment]
Can't easily update the survey without breaking what results we already
have.

Let's disable the pop up for now too as we have gratitude instead now.

---
Matt Lee
Creative Commons
Boston, MA, USA
