### ISSUE TITLE
Convert main screen of the app to swipeable tabs

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#314]
See prototype: http://invis.io/MH3FLVEB7

**Comment by AyoPrez** [comment]
Pretty cool. I would like to start (and finish) to work on it tomorrow. I will send a merge request when I complete it.

**Comment by perpetuatingcuriosity** [comment]
Hey @AyoPrez, I actually have this working on the develop-feed branch at the moment, and was just about to close the issue. 

Sorry to have you jumping between issues. I’m a bit behind on filing these (just to keep track of what we have completed).

**Comment by AyoPrez** [comment]
I just wanna help. I can do this (tablet-friendly issue), or anything else, but I'm a little lost because I don't know what can I do, and where.
