### ISSUE TITLE
“Flag” a photo endpoint

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#319]
We need to allow users to flag any inappropriate content in the Discover tab, in the event that such content exists.

**Comment by mattl** [comment]
A flagged photo should never appear to the user who flagged it again. Also, we'll should start thinking about a web based admin area for showing flagged images, etc.

**Comment by perpetuatingcuriosity** [comment]
Just to keep in mind our #337 “I don’t want to see this” approach will likely mean a lot of images that don’t need to be removed. This might affect our approach?

**Comment by robmyers** [comment]
API access implemented in 7a2f3d8958e5ff88761d1b4f7a20fdc0280ffc6d .

Users will not see images they have flagged.

Users cannot flag their own images.

Users must be logged in to flag images.

**Comment by perpetuatingcuriosity** [comment]
@robmyers, can you post of example/curl of the api request to flag an endpoint?

**Comment by perpetuatingcuriosity** [comment]
**ah sorry, I see we’re working on this in https://github.com/creativecommons/list/issues/337

**Comment by robmyers** [comment]
Heya. Yes there's a simple example at the end of docs/api.md . It's an actual test I ran locally, with the url swapped out, so it a call of that format doesn't work I've broken something badly. :-)
