### ISSUE TITLE
We need an endpoint that will return the current version of the app

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#330]
The endpoint should return whatever the newest release is. We can use it later to also keep track of api and web app versions.

For example: GET /api/info
```
[{
"api_version": "1.0",
"app_version": "3.0.1",
"webapp_version": "0.5",
}]
```

**Comment by mattl** [comment]
You'll find all the API stuff in webapp/api/

**Comment by robmyers** [comment]
Added in 94c4f83 .
