### ISSUE TITLE
Items are repeating themselves

### ISSUE THREAD

**Issue by orschiro** [creativecommons/list#331]
Hi all, 

I noticed that items are repeating themselves. 

Example:

I have submitted a picture for "truck". Upon request for new list items, it says again that "CC is in need for a photo of a truck". 

Is it possible to keep track of what photos the user had already submitted to prevent this double-counting? 

Thankfully,

Robert

**Comment by perpetuatingcuriosity** [comment]
Hi @orschiro! Yeah for sure! There’s some discussion in #290. Feel free to join the conversation :)

**Comment by orschiro** [comment]
@perpetuatingcuriosity 

Thanks for the reference!

Robert
