### ISSUE TITLE
Allow any registered user with to create a list

### ISSUE THREAD

**Issue by ryanmerkley** [creativecommons/list#34]
Any user of the List should be able to create a list of their own and share it. They should be prompted for a title, photographer's notes, metatags/hashtags, and the opportunity to upload an sample image.

This may also mean that later on, we would want the equivalent of "verified list makers" for partner orgs.

**Comment by ryanmerkley** [comment]
I'd like to tag this as MUST instead of SHOULD.

**Comment by perpetuatingcuriosity** [comment]
Right now any user can create list items from the android app. We discussed the webapp dealing with batch uploads/batch creation. Going to laterbase this for now.

**Comment by mattl** [comment]
I believe we're no longer doing this.
