### ISSUE TITLE
Ensure full phrase "The List Powered by Creative Commons" is on main website and wiki pages

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/list#343]
Including when published as MVP in December/January.

**Comment by mattl** [comment]
Ha. Right now it says "The List poweed by Creative Commons" -- isn't that good enough?

**Comment by mattl** [comment]
Added to footer.

**Comment by peterspdx** [comment]
:-)  Afraid not. Anyway, please keep it in mind. We need good exemplars to send USPTO in the next six months, and it's good practice to have it as the lead in.  Hum, looking at what you just now sent re footer.

**Comment by mattl** [comment]
You won't see it immediately, you'll need to look here: https://github.com/creativecommons/list/commit/a7730c048cb20d099df422f4e1a88b2f4f46a268

**Comment by mattl** [comment]
Diane, can this be closed?

**Comment by peterspdx** [comment]
I would prefer it not be relegated to a footnote. (And sorry for late reply, but wanted to see just what that looked like so I waited for the update). It's a brand, and should be treated as such. Not as a footnote IMHO.

Can we change this phrase:

Through The List, organizations will provide lists of locations, people, and events that they need photographs of.

to

The List powered by Creative Commons enables organizations to identify locations, people, and events that they want photographed.

**Comment by peterspdx** [comment]
(it also cleans up the dangling preposition :0))

**Comment by mattl** [comment]
Added in
https://github.com/creativecommons/list/commit/a22cb4140653d4f90e63fcc1e391fbd846da1a85

**Comment by peterspdx** [comment]
Thanks!
