### ISSUE TITLE
Update version data with current versions

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#344]
https://thelist.creativecommons.org/api/version should return the current version of the app, webapp and api.

For app_version, we’re currently at 4.0. 
@mattl can you confirm which versions we’re on for the webapp and api?

**Comment by mattl** [comment]
Update app to v4.0.0.

**Comment by robmyers** [comment]
@mattl - I thought we were using Version.Patch rather than Incompatible.Minor.Bugfix 

http://semver.org/

**Comment by mattl** [comment]
tl;dr. 4.0 is fine.

**Comment by robmyers** [comment]
Changed in 2adf3069f5625b8da24064a10ea5cf5b5eecbbf0 .
