### ISSUE TITLE
API Endpoints we’ll need

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#42]
<strong>Currently being used in the Test API (apitest)</strong>
- POST: new user (returns user object), new photo
- PUT: edit user full name, email, chosen items, chosen categories (sending array of item IDs and/or category IDs)
- GET: all users, all categories, all items, user by ID, category by ID, item by ID
- testing in app: get multiple items by sending array of item IDs

<br>
<strong>Needed Endpoints</strong>
- GET: random selection of items from user’s selection of categories in specific quantity
   i.e..: 20 random items from the People, Nature or Food categories, but excluding that Turkey Dinner item that is already in my list 
  - (also could request items from a single chosen category rather than a selection of items from any of the user’s chosen categories)

**Comment by perpetuatingcuriosity** [comment]
This week would it be possible to get:

PUT *api/category/:id* : save single user category preference based on ID
(don’t need it this week, but item requests (GET items) from the user should only come from these categories)

DELETE *api/users/userid/listid* : delete single item by id from user’s list

**Comment by mattl** [comment]
curl -v --data "skey=5b2e647dd5eca961d455b2e5e1e1edff" -X POST https://thelist.creativecommons/api/userlist/delete/2/10

**Comment by perpetuatingcuriosity** [comment]
For the next release we’re still missing: 

**PUT api/users/:userid/category/:id**
- save single user category preference based on ID
- (also only pick items from these categories when returned

**GET /api/photos/:x**
- returns “x” photos from a single list item
- response is array of JSONObjects

e.g.: GET https://thelist.creativecommons.org/api/photos/2
[{
"name":"dog",
"listid":"3",
"listUserName":"John Smith",
"listUserId":"3",
"makerid":"4",
"makername":"Wikipedia",
"imageURL": [url],
"votes":"123566",
"flag":0
},
{
"name":"cat",
"listid":"6",
"listUserName":"Jane Smith",
"listUserId":"4",
"makerid":"4",
"makername":"Wikipedia",
"imageURL": [url],
"votes":"459",
"flag":0
}]


**PUT /api/photos/:photoid/vote**
- add one vote to the photo with the matching id

**PUT /api/photos/:photoid/flag**
- add a flag to the photo with the matching id

**Comment by perpetuatingcuriosity** [comment]
Creating separate issues for each endpoint. If you want the full list, refer to general notes on MVP (#145).
