### ISSUE TITLE
When a user logs in the first time, what happens to their saved preferences?

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#44]
Users won’t be required to create a CCID until they upload a photo. However, as soon as they open the app, they will be asked to choose list categories and list items they like to receive tailored content right away.

Right now I’m saving these category and list item preferences locally, when the user is prompted to create an account, how will their preferences be added to the database?

1. At the moment I’m sending a user object will all the data (with arrays of IDs for chosen categories, and chosen items), e.g.:
user = {name:"John", email:"john@gmail.com, password:"somePassword", category: [1,2,3], items: [2,1,3]}

2. I could send 3 requests: POST user, PUT category, PUT items

What do you think, Matt?

**Comment by mattl** [comment]
Moving this to 0.3 when we'll worry about people signing up for the first time.

**Comment by mattl** [comment]
@perpetuatingcuriosity can you tell what we need to do here now? Is this handled by the category choices?

**Comment by perpetuatingcuriosity** [comment]
This should be handled by #149
