### ISSUE TITLE
Available Test Devices

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#49]
Currently I have access to:
HTC One (4.4.2)
Nexus 5 (5.0)
Nexus 4 (4.1–4.4?)
Nexus S (4.1.2)

Would you be able to send a few older devices? I’ll keep you up to date with how emulator testing is going with the older devices. 

side note: runs pretty well on Nexus S!

**Comment by mattl** [comment]
@perpetuatingcuriosity @wchwd Bringing a 2.3 phone to Canada. Try to contain your excitement.

**Comment by perpetuatingcuriosity** [comment]
But I cannot. :dancer:

**Comment by mattl** [comment]
Excitement was indeed not contained. I suspect @bartholomewdavid is now hiding the phone in their desk.
