### ISSUE TITLE
Support Android API v10

### ISSUE THREAD

**Issue by mattl** [creativecommons/list#5]
I believe this is the API level that lets us keep support for Android 2.3 devices.

Just so fully expand on this and make sure it's documented: we need to support devices without Google Play or Google Play Services, in addition to devices with those libraries.

**Comment by mattl** [comment]
Now you have your amazing phone, get it from @bartholomewdavid or @wchwd and let's see if we can get this thing running on it.

**Comment by perpetuatingcuriosity** [comment]
We’re supporting a minimum of API level 14 now
