### ISSUE TITLE
How are we handling logging in/signing up?

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#50]
Hey Matt, how are you thinking this will work? Anything I can start setting up on my end?

**Comment by mattl** [comment]
So, for now, please open https://login.creativecommons.org/ in a window for registration.

By 0.3 we need to have this in the app.

**Comment by ryanmerkley** [comment]
Ben raised some good questions regarding using Google as a login option. Is this the bug to consider that?

**Comment by mattl** [comment]
No, there's no bug for that right now as we're using CCID, and we have our own account system and sessions and everything.

**Comment by ryanmerkley** [comment]
Then let's create a separate bug for this and mark it 1.0. I'd like to have
the conversation with Ben before ship a public 1.0.

**Comment by mattl** [comment]
I think that is out of scope for this project. I'd like to see a way for CCID to support Google authentication down the line, but that's not what this issue is about.
