### ISSUE TITLE
BBC/other media corps getting free photos

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/list#52]
one group's reaction was why are we helping BBC get free photos? Shouldn't they pay for their photos, help employ photographers??

**Comment by ryanmerkley** [comment]
This really is a philosophical question about free culture and CC BY -- the statement about BBC would be true for any "commercial user" or user "who can afford to pay". That's just not what we believe -- if BBC wants a specific shot, they'll likely have to pay. If they happen to find the image they want, taken by a community member, then yes, they can use it -- and so can anyone else, including their competitors, citizen media, Wikipedia, etc.
