### ISSUE TITLE
Ensure the app can work without any dependency on Google Play Services

### ISSUE THREAD

**Issue by mattl** [creativecommons/list#6]
One target for the app is supporting alternative, free software friendly app distribution, so in addition to whatever we do with Play Store and Amazon Appstore, we should also support both F-Droid and sideloading the app directly as an apk.

Once we have some working code it would be good to set up a scheduled task to compile the app nightly.

**Comment by krt16s** [comment]
So the play-services can be removed from the dependency list (in gradle)?

**Comment by mvdan** [comment]
Just checked, it hasn't :)

**Comment by mattl** [comment]
@mvdan I'm confused. Are you saying play-services haven't been removed or that the app doesn't work without them?

**Comment by mvdan** [comment]
Sorry, I completely missed this.

I was about to update the app to 3.0 on F-Droid, but the app still requires google play services to build, which we don't have.
