### ISSUE TITLE
Fix confirmation email from email signup

### ISSUE THREAD

**Issue by elliotharmon** [creativecommons/list#69]
We should come up with a better solution now, since all of our mailing lists use the same confirmation email.

Here's the text I get when I sign up:

"Thank you for your interest in Creative Commons! To confirm your subscription to The List by Creative Commons, please click here. We'll send you occasional updates on CC’s projects and how you can help out."

The wording is confusing. The problem is that we need a way to signal in this email that people will *also* get general emails from CC. But we need to either have two different email templates or change the wording in such a way that it also makes sense when people are signing up *for* general emails from CC.

**Comment by mattl** [comment]
This list will go away around this period, and we should invite people to sign up to the general CC list.

**Comment by mattl** [comment]
This is now being debated internal to CC. https://github.com/creativecommons/internal/issues/6
