### ISSUE TITLE
Need session token from API when user logs in

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#84]

**Comment by perpetuatingcuriosity** [comment]
@mattl: Will this be up soon? I’ll need the token if we want to start working with Google AccountManager. (users can have a saved account on their phones for easy logins): http://udinic.wordpress.com/2013/04/24/write-your-own-android-authenticator/

**Comment by perpetuatingcuriosity** [comment]
#92 May take bit longer than I thought, ETA for when we’ll have session tokens?

**Comment by mattl** [comment]
Can you explain what you mean about session tokens? I'm not 100% sure if that's going to work or not.

**Comment by perpetuatingcuriosity** [comment]
Thinking session tokens is how we’ll do authenticated API calls:
- client authenticates with the server at /users/login
- users/login returns a token

We’ll use the token in all future API calls (like adding an item to the userlist) to prove that the user is allowed to make those calls. For security, after a set period of time, the token will expire and the user will have to login to get a new token.

This is where Google AccountManager will be super handy. Google Accounts Manager will create an account with the user’s login so when the token expires, it can handle re-authentication so the user never has to do a manual login.

Great article on AccountManager (More on the android end but may be handy.): https://udinic.wordpress.com/2013/04/24/write-your-own-android-authenticator/

**Comment by mattl** [comment]
Sessions. We have them.
