### ISSUE TITLE
About half the time, the upload photo function doesn't work. 

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/list#87]
In those instances, I get a blank screen. Then I have to back out and re-submit.

**Comment by janeatcc** [comment]
Same here.

**Comment by janeatcc** [comment]
This also happens using safari web browser on iphone 4

**Comment by mattl** [comment]
Can you try again? It will still fail, but it'll tell you why.

Can you also paste the filename of the image in question when this happens? For ease of use, I suggest doing this on a desktop browser.

**Comment by sarahpearson** [comment]
Just tried it again. Got this message: File naming error!

File name is 2013-11-07 10.33.09.jpg

**Comment by mattl** [comment]
Can you try again with an image named something like "cat.jpg"?

I think it might not like spaces in filenames.

**Comment by sarahpearson** [comment]
I got the same error after trying it as "cat.jpg" just now.

**Comment by mattl** [comment]
Moving this along. Doesn't seem to happen ever from the command line or the app, so I'm doing something stupid.

**Comment by janeatcc** [comment]
Still happening on Firefox 35.0.1

Got this error for a jpeg: "File naming error!"
