### ISSUE TITLE
Logging in is annoying, would like remember option

### ISSUE THREAD

**Issue by mindspillage** [creativecommons/list#92]
App does not remember login information, would like that to be an option because input on phones is annoying. (Even if it means someone who steals my phone might easily upload bad photos to the commons.)

**Comment by perpetuatingcuriosity** [comment]
@mattl I already have the code for this, just need the session token working to start testing it.

**Comment by perpetuatingcuriosity** [comment]
AccountManager w/ CCID accounts integrated. We could think about how to communicate this to the user, but for now done! :+1:
