### ISSUE TITLE
when I login using Safari using CCID, it doesn't bring me to a new page but instead I'm on the same page with a note that I've successfully logged in

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/list#93]
![screen shot 2015-01-05 at 1 54 32 pm](https://cloud.githubusercontent.com/assets/6127036/5620617/71eff08c-94e2-11e4-8341-2f4306731440.png)
there's no link that I can click to go to the main page or anywhere else for that matter.

**Comment by mattl** [comment]
Just to confirm: are you logging in on thelist.creativecommons.org or login.creativecommons.org?

It sounds like you're logging in at login.creativecommons.org -- which is fine, you're logged into CCID. if you go to the application now, and click login you should be logged in immediately.

**Comment by peterspdx** [comment]
but shouldn't there be a place to click from the general login page to head
to The List?  Yes, I can go back and find the other link and it lets me in,
but it's frustrating not to have places where I could then immediately go
from the general login page.



On Mon, Jan 5, 2015 at 1:56 PM, Matt Lee <notifications@github.com> wrote:

> Just to confirm: are you logging in on thelist.creativecommons.org or
> login.creativecommons.org?
>
> It sounds like you're logging in at login.creativecommons.org -- which is
> fine, you're logged into CCID. if you go to the application now, and click
> login you should be logged in immediately.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/list/issues/93#issuecomment-68789124>.
>



-- 
Diane M. Peters
General Counsel, Creative Commons
Portland, Oregon
http://creativecommons.org/staff#dianepeters

**Comment by mattl** [comment]
the general login page doesn't know about the list.

once you have a CCID, you can never go to the general login page yourself and instead just go to the list. the list will direct you to the login page if needed, and then take you back to the list.
