### ISSUE TITLE
Failed while adding a picture, then app crash

### ISSUE THREAD

**Issue by billymeinke** [creativecommons/list#94]
Chose to take a picture for an item, then nothing appeared different after upload. Tried to then "Choose Picture" from my device and got this error:

![2015-01-05 21 45 34](https://cloud.githubusercontent.com/assets/33296/5620761/d897f4c8-94fc-11e4-81df-69ed2a093705.png)

Selected the item to try once more and the app crashed.

**Comment by mattl** [comment]
Billy, tell us your Android version and device please :)

**Comment by billymeinke** [comment]
Samsung Note 3, Android 4.4.2 :)
