### ISSUE TITLE
My list items double up after a photo is uploaded

### ISSUE THREAD

**Issue by billymeinke** [creativecommons/list#95]
I successfully uploaded an image for an item, but when my list was refreshed, the remaining items now show up twice.

Screenshot:

https://www.dropbox.com/s/irv8o49yh77a2wi/2015-01-05%2021.59.09.png?dl=0

Samsung Note 3, Android 4.4.2

**Comment by mattl** [comment]
I think recycler views will handle this, so feel free to clone this out as a duplicate.

**Comment by perpetuatingcuriosity** [comment]
Just adjusted now the list updates. Should be good to go for Beta.
