### ISSUE TITLE
Minor design issues w/ soft keyboard when logging in

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#97]
- Soft keyboard stays up during upload confirmation screen and obscures content 
- AccountActivity: text does not shift upwards when text boxes are in focus (definitely on Nexus One, 4.1 ** check on other phones **)

**Comment by mattl** [comment]
This seemed a lot better in 0.1 but I think there's some work to be done still.

**Comment by perpetuatingcuriosity** [comment]
Just updated! Works well so I’m gonna close this. Might look at it again once we have the MVP in the refinement stage.
