### ISSUE TITLE
No way to get error information from API

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [creativecommons/list#99]
@Matt: We don’t necessarily have to deliver all the error information to the user, but if the API can send send me some more info about the errors I can:

1) Write helpful error messages for the user
2) Figure out why more of my own requests aren’t working so I don’t have to bug you :)

Can we have our own system of error codes to work with? Then I can write something to display the correct messages based on our created error codes.

**Comment by mattl** [comment]
I have implemented error codes on new functions. If you can open tickets for particular instances where we need better error responses, that's more helpful for me.
